// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class ListaParadas
{	
	//public Parada parada = 
	public List<Parada> listaParadas { get; set; } 
	public ListaParadas ()
	{
	}

	public ListaParadas (List<Parada> lista)
	{
		this.listaParadas = lista;
	}


}
