// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using SimpleJSON;

public class Parada
{
	public string nombreParada { get; set; }
	public string corredor { get; set; }
	public string x { get; set; }
	public string y { get; set; }
	
	public Parada ()
	{	
	}
	public Parada (string nombreParada, string corredor, string x, string y)
	{
		this.nombreParada = nombreParada;
		this.corredor = corredor;
		this.x = x;
		this.y = y;
	}
	public void convertFromJson(JSONNode json){
		this.nombreParada = json [0];
		this.corredor = json [1];
		this.x = json [2];
		this.y =  json [3];
	}
	public override string ToString(){
		//return "Parada: " + this.nombreParada + " , " + this.corredor + " , " + this.x + " , " + this.y;
		return this.nombreParada + " , " + this.y + " , " + this.x;
	}
}
