// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using SimpleJSON;
using System.Collections.Generic;

public class Parroquia
{
	public string nombreParroquia { get; set; }
	public string x { get; set; }
	public string y { get; set; }
	
	public Parroquia ()
	{	
	}
	public Parroquia (string nombreParroquia, string x, string y)
	{
		this.nombreParroquia = nombreParroquia;
		this.x = x;
		this.y = y;
	}
	public void convertFromJson(JSONNode json){
		this.nombreParroquia = json [0];
		this.x = json [1];
		this.y =  json [2];
	}
	public override string ToString(){
		return this.nombreParroquia + " , " + this.y + " , " + this.x;
	}

	public List<Parroquia> createList(){
		List<Parroquia> lista = new List<Parroquia> ();

		lista.Add (new Parroquia ("Belisario Quevedo","-0.188956","-78.50786770000002"));
		lista.Add (new Parroquia ("Carcelen","-0.0875297","-78.4689224"));
		lista.Add (new Parroquia ("Centro Histórico","-0.222846","-78.51709950000003"));
		lista.Add (new Parroquia ("Chilibulo","-0.2314799","-78.53485069999999"));
		lista.Add (new Parroquia ("Chillogallo","0.2858578","-78.57012480000003"));
		lista.Add (new Parroquia ("Chimbacalle","-0.24411","-78.51638939999998"));
		lista.Add (new Parroquia ("Cochapamba","-0.1487946","-78.50644729999999"));
		lista.Add (new Parroquia ("Comité del Pueblo","-0.1212609","-78.46098540000003"));
		lista.Add (new Parroquia ("Concepción","-0.141907","-78.49224270000002"));
		lista.Add (new Parroquia ("Cotocollao","-0.1212781","-78.50076569999999"));
		lista.Add (new Parroquia ("El Condado","-0.096076","-78.50360649999999"));
		lista.Add (new Parroquia ("El Inca","-0.1510624","-78.45814339999998"));
		lista.Add (new Parroquia ("Guamaní","-0.3443234","-78.56040689999998"));
		lista.Add (new Parroquia ("Iñaquito","-0.18779","-78.48087750000002"));
		lista.Add (new Parroquia ("Itchimbía","-0.2234065","-78.4993452"));
		lista.Add (new Parroquia ("Jipijapa","-0.1609663","-78.47963440000001"));
		lista.Add (new Parroquia ("Kennedy","-0.144193","-78.47803599999997"));
		lista.Add (new Parroquia ("La Argelia","-0.266667"," -78.5333"));
		lista.Add (new Parroquia ("La Ecuatoriana","-0.3086002","-78.5618265"));
		lista.Add (new Parroquia ("La Ferroviaria","-0.2636622","-78.51780959999996"));
		lista.Add (new Parroquia ("La Libertad","-0.2130889","-78.52917059999999"));
		lista.Add (new Parroquia ("La Mena","-0.2590975","-78.55756759999997"));
		lista.Add (new Parroquia ("Magdalena","-0.2313264","-78.5286812"));
		lista.Add (new Parroquia ("Mariscal Sucre","-0.2084643","-78.48940149999999"));
		lista.Add (new Parroquia ("Ponceano","-0.1212732","-78.48940149999999"));
		lista.Add (new Parroquia ("Puengasí","-0.25","-78.5"));
		lista.Add (new Parroquia ("Quitumbe","-0.2930405","-78.54975919999998"));
		lista.Add (new Parroquia ("Rumipamba","-0.1763215","-78.49508370000001"));
		lista.Add (new Parroquia ("San Bartolo","-0.2726816","-78.52381909999997"));
		lista.Add (new Parroquia ("San Juan","0.2084769","-78.50644729999999"));
		lista.Add (new Parroquia ("Solanda","-0.2665563","-78.53698059999999"));
		lista.Add (new Parroquia ("Turubamba","-0.2803692","-78.54124030000003"));


		return lista;
	}
}
